### ISSUE TITLE
Can I add more lines

### ISSUE THREAD

**Issue by aarvndhNG** [Dekay21/AnotherBroadcaster#2]
I can't add more lines @Dekay21

**Comment by Dekay21** [comment]
What exactly do you mean by that?
Do you mean configuring more than one broadcasting message in the config?

**Comment by aarvndhNG** [comment]
> What exactly do you mean by that? Do you mean configuring more than one broadcasting message in the config?

Yes i can't add more  @Dekay21

**Comment by Dekay21** [comment]
You're config should be something along the line of:
```json
[
    {
        "Text": "Message 1",
        "Color": "#ff00ff",
        "Interval": "2h30m"
    },
    {
        "Text": "Message 2",
        "Color": "#ff00ff",
        "Interval": "1h"
    }
]
```

**Comment by aarvndhNG** [comment]
Thanks so much
